name: Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Run custom action
        uses: ./github/actions/pull-latest-commit
        with:
          ec2-host: ${{ secrets.EC2_HOST }}
          ec2-user: ${{ secrets.EC2_USER }}
          ec2-ip: ${{ secrets.EC2_IP }}
          ec2-key: ${{ secrets.EC2_KEY }}
          ec2-port: ${{ vars.PORT }}
          backend-mongo-db-url: ${{ vars.BACKEND_MONGODB_URI }}
          backend-node-env: ${{ vars.BACKEND_NODE_ENV }}
          backend-ollama-base-url: ${{ vars.BACKEND_OLLAMA_BASE_URL }}
          backend-ollama-model: ${{ vars.BACKEND_OLLAMA_MODEL }}
          backend-port: ${{ vars.BACKEND_PORT }}
