name: Main

on:
  push:
    branches:
      - main

jobs:
  ssh-to-server:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH To Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ vars.PORT }} # trigger gha
          script: whoami
        run: |
          cd /home/ec2-user/ai-website-builder
          git pull origin main
          rm -rf .turbo
          npm run build
          pm2 stop ecosystem.config.js
          pm2 start ecosystem.config.js
